// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVGht5U49wGc3nlk1N-bU0aGaIxHrv1PU',
    appId: '1:695930256216:web:1924ca61ff4da6a0f8432d',
    messagingSenderId: '695930256216',
    projectId: 'crypto-list-app-9b9ad',
    authDomain: 'crypto-list-app-9b9ad.firebaseapp.com',
    storageBucket: 'crypto-list-app-9b9ad.appspot.com',
    measurementId: 'G-GJFE18Z256',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFP71JfFJu-y-GPGo39maliBhOV6nWBeo',
    appId: '1:695930256216:android:eb2b93f077414f20f8432d',
    messagingSenderId: '695930256216',
    projectId: 'crypto-list-app-9b9ad',
    storageBucket: 'crypto-list-app-9b9ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLxUb9HXVuyKv13DqGSBIR7MoiBaJUAsQ',
    appId: '1:695930256216:ios:6b72848be77ecb60f8432d',
    messagingSenderId: '695930256216',
    projectId: 'crypto-list-app-9b9ad',
    storageBucket: 'crypto-list-app-9b9ad.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLxUb9HXVuyKv13DqGSBIR7MoiBaJUAsQ',
    appId: '1:695930256216:ios:6b72848be77ecb60f8432d',
    messagingSenderId: '695930256216',
    projectId: 'crypto-list-app-9b9ad',
    storageBucket: 'crypto-list-app-9b9ad.appspot.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVGht5U49wGc3nlk1N-bU0aGaIxHrv1PU',
    appId: '1:695930256216:web:acd3767687af318ff8432d',
    messagingSenderId: '695930256216',
    projectId: 'crypto-list-app-9b9ad',
    authDomain: 'crypto-list-app-9b9ad.firebaseapp.com',
    storageBucket: 'crypto-list-app-9b9ad.appspot.com',
    measurementId: 'G-X7XQ5M8L61',
  );
}
